substitutions:
  name: "onju-voice"
  friendly_name: "Onju Voice"
  project_version: "1.2.0"
  device_description: "Onju Voice Satellite with ESPHome software and microWakeWord"

packages:
    - !include onju.yaml
    - !include wifi.yaml
    - !include ota.yaml